apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DemoAppTest
  # This is an extra long description with Markdown
  description: |
    [The Demo App](http://github.com) is an example API used to show features of the OpenAPI spec.
  links:
    - url: https://github.com/PavanKumarAS/test
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: team-C
  providesApis:
    - petstore
    - streetlights
    - hello-world
