version: '3.1'

services:
  testapp:
    image: testapp:1.0
    ports: 
      - 3030:3030
    networks:
      - mongo-network

  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mongo-network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: "mongo_ui"
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      #ME_CONFIG_MONGODB_URL: mongodb://mithun:pulickal@mongo-server:27017/
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=pavan
      - ME_CONFIG_BASICAUTH_PASSWORD=123456789
    networks:
      - mongo-network

networks:
  mongo-network:
    external: true

volumes:
  mongo-data: 
    driver: local